workflows:
    react-native-android:
        name: React Native Android
        max_build_duration: 120
        triggering:
            events:
                - push
            branch_patterns:
                - pattern: master
                  include: true
                  source: true
        scripts:
               - sudo docker build -t apache  .
